title: "FreeFem++ modules"
subtitle: "A collection of mathematically validated modules for FreeFem++"
description: "A collection of mathematically validated modules for FreeFem++"

url: "https://modules.freefem.org/"

markdown: kramdown

include: ["_modules"]

collections:
    modules:
      output: true
      permalink: /:collection/:path/
